import { defaultTheme } from '../themes/default'

const { globalCss } = defaultTheme

export const reset = globalCss({
  [`html,
  body,
  div,
  span,
  applet,
  object,
  iframe,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  p,
  blockquote,
  pre,
  a,
  abbr,
  acronym,
  address,
  big,
  cite,
  code,
  del,
  dfn,
  em,
  img,
  ins,
  kbd,
  q,
  s,
  samp,
  small,
  strike,
  strong,
  sub,
  sup,
  tt,
  var,
  b,
  u,
  i,
  center,
  dl,
  dt,
  dd,
  ol,
  ul,
  li,
  fieldset,
  form,
  label,
  legend,
  table,
  caption,
  tbody,
  tfoot,
  thead,
  tr,
  th,
  td,
  article,
  aside,
  canvas,
  details,
  embed,
  figure,
  figcaption,
  footer,
  header,
  hgroup,
  main,
  menu,
  nav,
  output,
  ruby,
  section,
  summary,
  time,
  mark,
  audio,
  video`]: {
    margin: '0',
    padding: '0',
    border: '0',
    fontSize: '100%',
    verticalAlign: 'baseline',
    boxSizing: 'border-box',
  },
  [`article,
  aside,
  details,
  figcaption,
  figure,
  footer,
  header,
  hgroup,
  main,
  menu,
  nav,
  section`]: {
    display: 'block',
  },
  '*[hidden]': { display: 'none' },
  body: { lineHeight: 1 },
  'ol, ul': { listStyle: 'none' },
  'blockquote, q': { quotes: 'none' },
  [`blockquote:before,
  blockquote:after,
  q:before,
  q:after`]: {
    content: 'none',
  },
  table: { borderCollapse: 'collapse', borderSpacing: '0' },
  button: { outline: 'none', cursor: 'pointer' },
  textarea: { fontFamily: 'sans-serif' },
  [`input[type='radio'],
  input[type='checkbox'],
  input[type='file']`]: {
    cursor: 'pointer',
  },
  [`input[type='text'],
  input[type='email'],
  input[type='password'],
  input[type='number'],
  input[type='tel'],
  input[type='search'],
  input[type='search']::-webkit-search-decoration,
  input[type='search']::-webkit-search-cancel-button,
  input[type='search']::-webkit-search-results-button,
  input[type='search']::-webkit-search-results-decoration,
  textarea`]: {
    '-webkit-appearance': 'none',
    '-moz-appearance': 'none',
  },
})
